language: node_js
node_js:
- '0.11'
- '0.10'

before_install:
  - gem update --system
  - gem install sass --version "=3.4.6"
  - gem install compass --version "=1.0.1"

env:
  - NODE_ENV="development"
  - NODE_ENV="production"